### PR TITLE
Increase test coverage

### LINKED ISSUE #3: Improve code coverage
* **Do you want to request a *feature* or report a *bug*?**
N/A

* **What is the current behavior?**
Code coverage is too low 52%

* **What is the expected behavior?**
We need to add more unit tests to reach 90%.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by ChamseddineBhd**
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

fix #3 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
increase test coverage

**What is the current behavior?** *(You can also link to an open issue here)*

coverage 52%

**What is the new behavior (if this is a feature change)?**

coverage > 80%

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataController.java [hunk 1]
```diff
@@ -58,7 +54,6 @@
     public ResponseEntity<List<SubstationGeoData>> getSubstations(@RequestParam UUID networkUuid,
                                                                   @RequestParam(required = false) List<String> countries) {
         Set<Country> countrySet = toCountrySet(countries);
-        LOGGER.info("Loading substations geo data for countries {} of network '{}'", countrySet, networkUuid);
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataController.java]: Why did you remove these logs?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java [hunk 2]
```diff
@@ -50,6 +50,8 @@
         // TODO filter by country
         StopWatch stopWatch = StopWatch.createStarted();
 
+        LOGGER.info("countries size {}", countries.size());
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: This should be a trace log not an info.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/GeoDataApplicationTest.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+import static org.springframework.test.context.TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS;
+
+@RunWith(SpringRunner.class)
+@ContextConfiguration(classes = {GeoDataApplication.class})
+@TestExecutionListeners(listeners = {CassandraUnitDependencyInjectionTestExecutionListener.class,
+        CassandraUnitTestExecutionListener.class},
+        mergeMode = MERGE_WITH_DEFAULTS)
+@CassandraDataSet(value = "geo_data.cql", keyspace = CassandraConstants.KEYSPACE_GEO_DATA)
+@EmbeddedCassandra
+public class GeoDataApplicationTest {
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/GeoDataApplicationTest.java]: What is the purpose of this unit test? It has no added value (just one non null assert).

File: geo-data-server/src/test/java/com/powsybl/geodata/server/dto/LineGeoDataTest.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+
+        assertEquals("l", lineGeoData.getId());
+        assertEquals(Country.FR, lineGeoData.getCountry1());
+        assertEquals(Country.FR, lineGeoData.getCountry2());
+        assertTrue(lineGeoData.getCoordinates().isEmpty());
+
+        LineGeoData.LineGeoDataBuilder lineGeoDataBuilder  =  LineGeoData.builder();
+        lineGeoDataBuilder.id("testId");
+
+        assertEquals("LineGeoData.LineGeoDataBuilder(id=testId, country1=null, country2=null, coordinates=null)", lineGeoDataBuilder.toString());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/dto/LineGeoDataTest.java]: Why do you test the builder instance and not the built object?

File: geo-data-server/src/test/java/com/powsybl/geodata/server/dto/SubstationGeoDataTest.java [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+        SubstationGeoData substationGeoData = new SubstationGeoData("id", Country.FR, new Coordinate(1, 1));
+
+        assertEquals("id", substationGeoData.getId());
+        assertEquals(Country.FR, substationGeoData.getCountry());
+        assertEquals(1, substationGeoData.getCoordinate().getLat(), 0);
+        assertEquals(1, substationGeoData.getCoordinate().getLon(), 0);
+
+        SubstationGeoData.SubstationGeoDataBuilder substationGeoDataBuilder = SubstationGeoData.builder();
+        substationGeoDataBuilder.id("testID");
+        assertEquals("SubstationGeoData.SubstationGeoDataBuilder(id=testID, country=null, coordinate=null)", substationGeoDataBuilder.toString());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/dto/SubstationGeoDataTest.java]: Same remark.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java [hunk 6]
```diff
@@ -0,0 +1,22 @@
+package com.powsybl.geodata.server.repositories;
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java]: Missing header

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+
+import com.powsybl.geodata.extensions.Coordinate;
+import org.junit.Test;
+
+import java.util.Arrays;
+import java.util.List;
+
+import static org.junit.Assert.assertEquals;
+
+public class CoordinateEntityTest {
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java]: Missing author.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+
+    @Test
+    public void test() {
+        List<CoordinateEntity> coordinateEntities =  CoordinateEntity.create(Arrays.asList(new Coordinate(1, 1), new Coordinate(2, 2)));
+        assertEquals(2, coordinateEntities.size(), 0);
+
+        CoordinateEntity.CoordinateEntityBuilder coordinateEntityBuilder =  CoordinateEntity.builder().lat(2).lon(2);
+        assertEquals("CoordinateEntity.CoordinateEntityBuilder(lat=2.0, lon=2.0)", coordinateEntityBuilder.toString());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java]: Same remark, I do not see the purpose to assert the builder state.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/LineCustomRepositoryTest.java [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+    public void test() {
+
+        lineRepository.save(LineEntity.builder()
+                .country(String.valueOf(Country.FR))
+                .id("testId")
+                .country("FR")
+                .otherCountry("BE")
+                .build());
+
+        assertEquals(1, lineCustomRepository.getLines().size());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/LineCustomRepositoryTest.java]: You should add more asserts. It is a very weak unit test to only test the number of line.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/LineRepositoryTest.java [hunk 10]
```diff
@@ -43,13 +43,17 @@ public void test() {
...
+        LineEntity.LineEntityBuilder lineEntityBuilder = LineEntity.builder();
+        lineEntityBuilder.country("FR")
                 .otherCountry("BE")
                 .side1(false)
                 .id("lineID")
-                .coordinates(coordinateEntities)
-                .build());
+                .coordinates(coordinateEntities);
+
+        assertEquals("LineEntity.LineEntityBuilder(country=FR, id=lineID, side1=false, otherCountry=BE, coordinates=[CoordinateEntity(lat=11.0, lon=12.0), CoordinateEntity(lat=13.0, lon=14.1)])", lineEntityBuilder.toString());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/LineRepositoryTest.java]: Same remark, assert the built object and not the builder.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/SubstationRepositoryTest.java [hunk 11]
```diff
@@ -38,14 +39,23 @@
...
-        repository.save(SubstationEntity.builder()
+
+        SubstationEntity.SubstationEntityBuilder substationEntityBuilder = SubstationEntity.builder()
                 .country("FR")
                 .id("ID")
-                .coordinate(CoordinateEntity.builder().lat(3).lon(2).build())
-                .build());
+                .coordinate(CoordinateEntity.builder().lat(3).lon(2).build());
+
+        assertEquals("SubstationEntity.SubstationEntityBuilder(country=FR, id=ID, coordinate=CoordinateEntity(lat=3.0, lon=2.0))", substationEntityBuilder.toString());
```
Comment (geofjamg) [inline geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/SubstationRepositoryTest.java]: Same remark.

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 2 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: just to avoid sonar major error : unused parameter  countries.
i'll change info -> trace

Comment (geofjamg) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: So you can remove the log and keep the Sonar issue. That will be solved once countries will be used in tha Cassandra query.

File: geo-data-server/src/test/java/com/powsybl/geodata/server/dto/LineGeoDataTest.java (hunk 4 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/test/java/com/powsybl/geodata/server/dto/LineGeoDataTest.java]: i should test both of them.
if i don't test toString method, coverage for that class decrease from 100% to 56% !

File: geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java (hunk 8 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/test/java/com/powsybl/geodata/server/repositories/CoordinateEntityTest.java]: Same

File: geo-data-server/src/test/java/com/powsybl/geodata/server/dto/SubstationGeoDataTest.java (hunk 5 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/test/java/com/powsybl/geodata/server/dto/SubstationGeoDataTest.java]: Same

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataController.java (hunk 1 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataController.java]: to resolve a sonar issue, Sonar don't recommend to call a logger in an endpoint method.

Comment (geofjamg) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataController.java]: So move it to service side instead of removing it

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java [hunk 12]
```diff
@@ -60,7 +62,11 @@
         return substationsGeoDataDB;
     }
 
-    public List<SubstationGeoData> getSubstations(Network network, Set<Country> countries) {
+    List<SubstationGeoData> getSubstations(Network network, Set<Country> countries) {
+        String countiesSet = countries.toString();
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: I am wondering if it is not a Sonar false alarm as here input is parsed to Country enum and there is no risk of log forging?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java [hunk 13]
```diff
@@ -210,12 +216,20 @@ private static SubstationGeoData calculateCentroidGeoData(Substation substation,
         return neighbours;
     }
 
-    public void saveSubstations(List<SubstationGeoData> substationsGeoData) {
+    void saveSubstations(List<SubstationGeoData> substationsGeoData) {
+        String listSize = substationsGeoData.size() + "";
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same here we only print the size, there is no potiential log forging issue?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java [hunk 14]
```diff
@@ -210,12 +216,20 @@ private static SubstationGeoData calculateCentroidGeoData(Substation substation,
...
+        listSize = listSize.replaceAll(REGEX, "_");
+        LOGGER.info("Saving {} substations geo data", listSize);
+
         List<SubstationEntity> substationEntities = substationsGeoData.stream().map(SubstationEntity::create).collect(Collectors.toList());
         substationRepository.saveAll(substationEntities);
     }
 
-    public void saveLines(List<LineGeoData> linesGeoData) {
+    void saveLines(List<LineGeoData> linesGeoData) {
+        String listSize = linesGeoData.size() + "";
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java [hunk 15]
```diff
@@ -228,7 +242,11 @@ public void saveLines(List<LineGeoData> linesGeoData) {
         lineRepository.saveAll(linesEntities);
     }
 
-    public List<LineGeoData> getLines(Network network, Set<Country> countries) {
+    List<LineGeoData> getLines(Network network, Set<Country> countries) {
+        String countiesSet = countries.toString();
```
Comment (geofjamg) [inline geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 13 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Sonar explanation :
User provided data, such as URL parameters, POST data payloads or cookies, should always be considered **untrusted and tainted**. Applications logging tainted data could enable an attacker to inject characters that would break the log file pattern. This could be used to block monitors and SIEM (Security Information and Event Management) systems from detecting other malicious events.

Here, substationsGeoData is considered as unstrusted parameter. sonar prevent use the result of substationsGeoData.size() is the log trace.

Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: X.replaceAll("\"[\\n|\\r|\\t]\"", "_") should be applied before using the result as a log input.

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 14 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 12 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same reason as below.

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 15 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Same

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 13 above)
Comment (geofjamg) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: But here we only log the size, so we cannot have line breaks added to logs?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 12 above)
Comment (geofjamg) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Each of the input country is passed to Country.valueOf, if a malicious line break is introduced we will ony have an enum parse exception.

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 13 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Alright, that doesn't make sense!  should we ignore that issue ?

File: geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java (hunk 12 above)
Comment (ChamseddineBhd) [reply geo-data-server/src/main/java/com/powsybl/geodata/server/GeoDataService.java]: Alright,
